In [23]:
import numpy as np

In [24]:
a = np.arange(10)[1:].reshape([9,1])

In [25]:
b = a.reshape([9])

In [27]:
a*b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [26]:
[(a*b)[i,i:] for i in range(9) ]

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 9, 12, 15, 18, 21, 24, 27]),
 array([16, 20, 24, 28, 32, 36]),
 array([25, 30, 35, 40, 45]),
 array([36, 42, 48, 54]),
 array([49, 56, 63]),
 array([64, 72]),
 array([81])]

In [28]:
print ('\n'.join([' '.join(['%s*%s=%-2s' % (j,i,i*j) for j in range(1,i+1)]) for i in range(1,10)]))

1*1=1 
1*2=2  2*2=4 
1*3=3  2*3=6  3*3=9 
1*4=4  2*4=8  3*4=12 4*4=16
1*5=5  2*5=10 3*5=15 4*5=20 5*5=25
1*6=6  2*6=12 3*6=18 4*6=24 5*6=30 6*6=36
1*7=7  2*7=14 3*7=21 4*7=28 5*7=35 6*7=42 7*7=49
1*8=8  2*8=16 3*8=24 4*8=32 5*8=40 6*8=48 7*8=56 8*8=64
1*9=9  2*9=18 3*9=27 4*9=36 5*9=45 6*9=54 7*9=63 8*9=72 9*9=81
